### ISSUE TITLE
(React) Element type is invalid

### ISSUE THREAD

**Issue by arsalannury** [MajidAlinejad/Iran-License-Plate#3]
I'm using this package but it doesn't render anything.
I have an error on the first render which you can see here:

![Screenshot (24)](https://user-images.githubusercontent.com/82847525/235843096-8cd3218a-554b-47ac-a2aa-f26842b2fb40.png)

**note**: react app created with Vite.
react version: 18.2.0

**Comment by MajidAlinejad** [comment]
Thanks for reporting the problem. I fix it as soon as I can.
Sincerely Majid Alinejad.

**Comment by MajidAlinejad** [comment]
@arsalannury now you can use our package in Vite. 
reason for the problem was the tsconfig.json configuration. Apparently, the Vite has issues with "module": "CommonJs" and I had to use "ES6" for the package.
thanks again and I wish you the best.
